title: tyamazaki
email: rd070672@gmail.com
description: >  # this means to ignore newlines until "baseurl:"
  This portfolio website is designed by tyamazaki (Takahiro Yamazaki), who is a materials scientist/researcher.
baseurl: "https://tyamazaki.com/index"  # the subpath of your site, e.g. /blog
url: "https://tyamazaki.com"  # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  rd070672
theme: minima
plugins:
  - jekyll-feed

permalink: pretty